name: Build Windows Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build-windows:
    name: Build Windows EXE
    runs-on: windows-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop

      - name: Ensure Windows folder exists
        shell: pwsh
        run: |
          if (!(Test-Path "windows")) {
            flutter create --platforms=windows .
          }

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze without blocking release
        run: flutter analyze lib --no-fatal-infos --no-fatal-warnings || true

      - name: Build Windows release
        run: flutter build windows --release

      - name: Zip release folder
        shell: pwsh
        run: |
          Compress-Archive -Path build\windows\x64\runner\Release\* -DestinationPath AcougueDoLeleco-Windows.zip -Force

      - name: Upload Windows build
        uses: actions/upload-artifact@v4
        with:
          name: AcougueDoLeleco-Windows
          path: AcougueDoLeleco-Windows.zip
